export const SHOP_DATA = [
	{
		title: "phones",
		items: [
			{
				id: 1,
				imageUrl: "https://i.imgur.com/feFijXF.jpg",
				name: "iPhone 13 Pro Max",
				category: "phones",
				price: 1099,
				color: "Sierra Blue",
				storage: "256GB",
			},
			{
				id: 11,
				imageUrl: "https://i.imgur.com/5SyeaCG.jpg",
				name: "iPhone SE",
				category: "phones",
				price: 399,
				color: "Red",
				storage: "128GB",
			},
		],
	},
	{
		title: "tablets",
		items: [
			{
				id: 2,
				imageUrl: "https://i.imgur.com/Ot1EXeQ.jpg",
				name: "iPad Air (4th Generation)",
				category: "tablets",
				price: 599,
				color: "Rose Gold",
				storage: "64GB",
			},
			{
				id: 10,
				imageUrl: "https://i.imgur.com/8N7UlPN.jpg",
				name: "iPad Pro (5th Generation)",
				category: "tablets",
				price: 1099,
				color: "Silver",
				storage: "1TB",
			},
		],
	},
	{
		title: "laptops",
		items: [
			{
				id: 3,
				imageUrl: "https://i.imgur.com/jPwsSQa.jpg",
				name: "MacBook Pro (16-inch)",
				category: "laptops",
				price: 2399,
				color: "Space Gray",
				storage: "512GB",
			},
			{
				id: 13,
				imageUrl: "https://i.imgur.com/JiFlkLu.jpg",
				name: "MacBook Air (M1)",
				category: "laptops",
				price: 999,
				color: "Gold",
				storage: "256GB",
			},
		],
	},
	{
		title: "watches",
		items: [
			{
				id: 4,
				imageUrl: "https://i.imgur.com/QamOKth.jpg",
				name: "Apple Watch Series 7",
				category: "watches",
				price: 399,
				color: "Midnight",
				storage: "16GB",
			},
			{
				id: 15,
				imageUrl: "https://i.imgur.com/3iDH9pq.jpg",
				name: "Apple Watch SE",
				category: "watches",
				price: 279,
				color: "Silver",
				storage: "32GB",
			},
		],
	},

	{
		title: "desktops",
		items: [
			{
				id: 6,
				imageUrl: "https://i.imgur.com/5tYUtRy.jpg",
				name: "iMac (24-inch, M1)",
				category: "desktops",
				price: 1299,
				color: "Blue",
				storage: "256GB",
			},
			{
				id: 9,
				imageUrl: "https://i.imgur.com/huvXrqq.jpg",
				name: "Mac mini",
				category: "desktops",
				price: 699,
				color: "Silver",
				storage: "256GB",
			},
			{
				id: 16,
				imageUrl: "https://i.imgur.com/pu86PP3.jpg",
				name: "iMac Pro",
				category: "desktops",
				price: 4999,
				color: "Space Gray",
				storage: "1TB",
			},
			{
				id: 18,
				imageUrl: "https://i.imgur.com/4E5TtdQ.jpg",
				name: "Mac Pro",
				category: "desktops",
				price: 5999,
				color: "Silver",
				storage: "256GB",
			},
		],
	},

	{
		title: "speakers",
		items: [
			{
				id: 7,
				imageUrl: "https://i.imgur.com/Ir4DaT8.jpg",
				name: "HomePod Mini",
				category: "speakers",
				price: 99,
				color: "Space Gray",
				storage: "N/A",
			},
		],
	},

	{
		title: "accessories",
		items: [
			{
				id: 12,
				imageUrl: "https://i.imgur.com/KRgUUn2.jpg",
				name: "Apple Pencil (2nd Generation)",
				category: "accessories",
				price: 129,
				color: "White",
				storage: "N/A",
			},
			{
				id: 20,
				imageUrl: "https://i.imgur.com/Bj6un1q.jpg",
				name: "Magic Keyboard",
				category: "accessories",
				price: 299,
				color: "Silver",
				storage: "N/A",
			},
		],
	},
	{
		title: "TVs",
		items: [
			{
				id: 17,
				imageUrl: "https://i.imgur.com/ER0LSMg.jpg",
				name: "Apple TV HD",
				category: "TVs",
				price: 149,
				color: "White",
				storage: "32GB",
			},
			{
				id: 8,
				imageUrl: "https://i.imgur.com/2TzOx75.jpg",
				name: "Apple TV 4K",
				category: "TVs",
				price: 179,
				color: "Black",
				storage: "32GB",
			},
		],
	},

	{
		title: "headphones",
		items: [
			{
				id: 5,
				imageUrl: "https://i.imgur.com/eJIicqK.jpg",
				name: "AirPods Pro",
				category: "headphones",
				price: 249,
				color: "White",
				storage: "N/A",
			},
			{
				id: 19,
				imageUrl: "https://i.imgur.com/61o9CAE.jpg",
				name: "Beats Studio Buds",
				category: "headphones",
				price: 149,
				color: "Black",
				storage: "N/A",
			},
		],
	},
];
